import { S, type HeroRun } from "./heroTypes";

/** Runs 09–15. */
export const RUNS_B: HeroRun[] = [
  {
    id: "forksmith",
    project: "forksmith",
    prompt: "a CLI that cleans up stale git branches",
    target: "cli tool",
    stack: ["Node", "Commander", "npm"],
    spec: { files: 7, cost: "$0.28", time: "~5 min" },
    stages: [S.scaffold, S.api, S.tests, S.security, S.perf, S.build],
    log: [
      { tone: "coder", text: "building branch scanner" },
      { tone: "reviewer", text: "auditing prune command" },
      { tone: "flag", text: "flag · destructive op without dry-run" },
      { tone: "ok", text: "confirm gate + --dry-run · verified" },
      { tone: "infra", text: "shell injection surface · sanitised" },
      { tone: "reviewer", text: "14 tests green · 0 flakes" },
    ],
    files: [
      {
        name: "prune.ts",
        path: "src/commands/",
        lines: [
          'import { execFile } from "node:child_process";',
          "",
          "export async function prune(opts: Options) {",
          "  const stale = await findStale(opts.days);",
          "",
          "  if (opts.dryRun) {",
          "    stale.forEach((b) => console.log(`would delete ${b}`));",
          "    return;",
          "  }",
          "",
          "  if (!(await confirm(stale.length))) return;",
          '  await execFile("git", ["branch", "-D", ...stale]);',
          "}",
        ],
      },
      {
        name: "scan.ts",
        path: "src/lib/",
        lines: [
          "const DAY = 86_400_000;",
          "",
          "export async function findStale(days: number) {",
          "  const branches = await listBranches();",
          "  const cutoff = Date.now() - days * DAY;",
          "",
          "  return branches",
          "    .filter((b) => b.lastCommit < cutoff)",
          "    .filter((b) => !PROTECTED.has(b.name))",
          "    .map((b) => b.name);",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "forksmith", title: "7 stale branches", badge: "dry run" },
      {
        t: "list",
        label: "candidates",
        rows: [
          { name: "feature/old-auth", meta: "8mo", state: "warn" },
          { name: "fix/typo-header", meta: "6mo", state: "warn" },
          { name: "chore/deps-bump", meta: "5mo", state: "warn" },
          { name: "main", meta: "protected", state: "off" },
        ],
      },
      {
        t: "kpi",
        items: [
          { label: "scanned", value: "42" },
          { label: "stale", value: "7" },
          { label: "protected", value: "3" },
          { label: "freed", value: "1.2GB" },
        ],
      },
    ],
  },

  {
    id: "roamlog",
    project: "roamlog",
    prompt: "a travel journal with an interactive map",
    target: "web app",
    stack: ["React", "Mapbox", "Postgres"],
    spec: { files: 13, cost: "$0.62", time: "~8 min" },
    stages: [S.scaffold, S.db, S.api, S.perf, S.cache, S.seo, S.build],
    log: [
      { tone: "coder", text: "building trip timeline" },
      { tone: "infra", text: "geospatial index · postgis enabled" },
      { tone: "reviewer", text: "auditing map layer" },
      { tone: "flag", text: "flag · 4k markers block main thread" },
      { tone: "ok", text: "clustered to canvas layer · 60fps" },
      { tone: "infra", text: "tiles cached at edge · 24h ttl" },
    ],
    files: [
      {
        name: "cluster.ts",
        path: "src/lib/",
        lines: [
          'import Supercluster from "supercluster";',
          "",
          "export function buildIndex(points: Pin[]) {",
          "  const index = new Supercluster({",
          "    radius: 48,",
          "    maxZoom: 16,",
          "  });",
          "",
          "  index.load(points.map(toFeature));",
          "  return index;",
          "}",
        ],
      },
      {
        name: "Timeline.tsx",
        path: "src/components/",
        lines: [
          'import { useTrips } from "../lib/useTrips";',
          "",
          "export function Timeline() {",
          "  const { trips } = useTrips();",
          "",
          "  return (",
          '    <ol className="timeline">',
          "      {trips.map((t) => (",
          "        <li key={t.id}>",
          "          <Entry trip={t} />",
          "        </li>",
          "      ))}",
          "    </ol>",
          "  );",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "2026", title: "9 countries", badge: "42 entries" },
      {
        t: "map",
        label: "where you've been",
        pins: [
          { x: 22, y: 40 },
          { x: 34, y: 28, live: true },
          { x: 48, y: 52 },
          { x: 61, y: 34 },
          { x: 72, y: 60 },
          { x: 84, y: 44 },
          { x: 15, y: 66 },
        ],
        caption: "tap a pin to open the entry",
      },
      {
        t: "feed",
        items: [
          { title: "Lisbon · rooftop sunsets", meta: "6 photos · Apr 22" },
          { title: "Porto · river walk", meta: "11 photos · Apr 19" },
          { title: "Madrid · late tapas", meta: "8 photos · Apr 15" },
        ],
      },
    ],
  },

  {
    id: "leaseiq",
    project: "leaseiq",
    prompt: "a rent tracker with automatic payment reminders",
    target: "web app",
    stack: ["React", "Postgres", "Cron"],
    spec: { files: 12, cost: "$0.55", time: "~7 min" },
    stages: [S.scaffold, S.db, S.auth, S.api, S.security, S.tests, S.build],
    log: [
      { tone: "coder", text: "modelling leases + payments" },
      { tone: "infra", text: "cron worker · timezone-safe schedule" },
      { tone: "reviewer", text: "auditing reminder job" },
      { tone: "flag", text: "flag · duplicate sends on retry" },
      { tone: "ok", text: "idempotency ledger · verified" },
      { tone: "infra", text: "pii encrypted at rest · aes-256" },
    ],
    files: [
      {
        name: "reminders.ts",
        path: "src/server/",
        lines: [
          'import { db } from "./client";',
          "",
          "export async function sendDue(today: Date) {",
          "  const due = await db.leases.dueOn(today);",
          "",
          "  for (const lease of due) {",
          "    const key = `${lease.id}:${iso(today)}`;",
          "    if (await alreadySent(key)) continue;",
          "",
          "    await mail(lease.tenantEmail, rentTemplate(lease));",
          "    await markSent(key);",
          "  }",
          "}",
        ],
      },
      {
        name: "schedule.ts",
        path: "src/lib/",
        lines: [
          "export function nextDueDate(day: number, from: Date) {",
          "  const next = new Date(from);",
          "  next.setDate(day);",
          "",
          "  if (next <= from) {",
          "    next.setMonth(next.getMonth() + 1);",
          "  }",
          "",
          "  return next;",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "portfolio", title: "6 units · 100% occupied", badge: "on time" },
      {
        t: "kpi",
        items: [
          { label: "collected", value: "$9.4k" },
          { label: "pending", value: "$1.6k" },
          { label: "late", value: "0" },
          { label: "yield", value: "6.2%" },
        ],
      },
      {
        t: "table",
        cols: ["unit", "due", "status"],
        rows: [
          ["12A · Oakwood", "May 1", "paid"],
          ["4C · Riverside", "May 1", "paid"],
          ["7B · Oakwood", "May 3", "pending"],
          ["2F · Hillcrest", "May 5", "pending"],
        ],
      },
    ],
  },

  {
    id: "mealmind",
    project: "mealmind",
    prompt: "a meal planner that builds a grocery list",
    target: "web app",
    stack: ["React", "Postgres", "PWA"],
    spec: { files: 12, cost: "$0.51", time: "~7 min" },
    stages: [S.scaffold, S.db, S.state, S.perf, S.a11y, S.cache, S.build],
    log: [
      { tone: "coder", text: "building planner grid" },
      { tone: "infra", text: "service worker · offline shell cached" },
      { tone: "reviewer", text: "auditing list merge" },
      { tone: "flag", text: "flag · duplicate units not normalised" },
      { tone: "ok", text: "unit conversion table · verified" },
      { tone: "reviewer", text: "installable pwa · manifest valid" },
    ],
    files: [
      {
        name: "groceries.ts",
        path: "src/lib/",
        lines: [
          'import { toBase } from "./units";',
          "",
          "export function buildList(recipes: Recipe[]) {",
          "  const merged = new Map<string, number>();",
          "",
          "  for (const r of recipes) {",
          "    for (const ing of r.ingredients) {",
          "      const grams = toBase(ing.qty, ing.unit);",
          "      merged.set(ing.name, (merged.get(ing.name) ?? 0) + grams);",
          "    }",
          "  }",
          "",
          "  return [...merged].map(([name, grams]) => ({ name, grams }));",
          "}",
        ],
      },
      {
        name: "units.ts",
        path: "src/lib/",
        lines: [
          "const TO_GRAMS: Record<string, number> = {",
          "  g: 1,",
          "  kg: 1000,",
          "  oz: 28.35,",
          "  lb: 453.6,",
          "};",
          "",
          "export function toBase(qty: number, unit: string) {",
          "  const factor = TO_GRAMS[unit];",
          "  if (!factor) throw new Error(`unknown unit ${unit}`);",
          "  return qty * factor;",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "this week", title: "14 meals planned", badge: "offline ready" },
      {
        t: "cards",
        items: [
          { title: "Mon · Miso salmon", sub: "28 min · 540 kcal" },
          { title: "Tue · Lentil ragu", sub: "35 min · 480 kcal", tag: "veg" },
          { title: "Wed · Chicken bowls", sub: "22 min · 610 kcal" },
          { title: "Thu · Shakshuka", sub: "18 min · 420 kcal", tag: "veg" },
        ],
      },
      {
        t: "list",
        label: "grocery list · 18 items",
        rows: [
          { name: "Salmon fillets", meta: "600 g", state: "on" },
          { name: "Green lentils", meta: "500 g", state: "on" },
          { name: "Greek yoghurt", meta: "1 kg", state: "off" },
          { name: "Sourdough", meta: "2 loaves", state: "off" },
        ],
      },
    ],
  },

  {
    id: "clipvault",
    project: "clipvault",
    prompt: "an API that screenshots any url and caches it",
    target: "api service",
    stack: ["Node", "Playwright", "S3"],
    spec: { files: 10, cost: "$0.47", time: "~6 min" },
    stages: [S.scaffold, S.api, S.rate, S.cache, S.security, S.tests, S.build],
    log: [
      { tone: "coder", text: "building capture endpoint" },
      { tone: "infra", text: "headless pool · 4 warm workers" },
      { tone: "reviewer", text: "auditing url handling" },
      { tone: "flag", text: "flag · SSRF via internal ip range" },
      { tone: "ok", text: "allowlist + dns pin · verified" },
      { tone: "infra", text: "s3 cache · content-hash keys" },
    ],
    files: [
      {
        name: "capture.ts",
        path: "src/routes/",
        lines: [
          'import { assertPublicUrl } from "../lib/guard";',
          "",
          "export async function GET(req: Request) {",
          '  const url = new URL(req.url).searchParams.get("url");',
          "  assertPublicUrl(url);",
          "",
          "  const key = hash(url);",
          "  const cached = await s3.get(key);",
          "  if (cached) return image(cached);",
          "",
          "  const shot = await pool.screenshot(url);",
          "  await s3.put(key, shot);",
          "  return image(shot);",
          "}",
        ],
      },
      {
        name: "guard.ts",
        path: "src/lib/",
        lines: [
          "const BLOCKED = [/^127\\./, /^10\\./, /^192\\.168\\./];",
          "",
          "export function assertPublicUrl(raw: string | null) {",
          '  if (!raw) throw new HttpError(400, "url required");',
          "",
          "  const { hostname, protocol } = new URL(raw);",
          '  if (protocol !== "https:") throw new HttpError(400, "https only");',
          "",
          "  const ip = resolveSync(hostname);",
          "  if (BLOCKED.some((re) => re.test(ip))) {",
          '    throw new HttpError(403, "private range blocked");',
          "  }",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "api", title: "clipvault/v1", badge: "99.98% up" },
      {
        t: "kpi",
        items: [
          { label: "p50", value: "310ms" },
          { label: "p95", value: "1.2s" },
          { label: "cache hit", value: "87%" },
          { label: "req/day", value: "48k" },
        ],
      },
      {
        t: "table",
        cols: ["endpoint", "calls", "p95"],
        rows: [
          ["GET /capture", "31.2k", "1.2s"],
          ["GET /cached", "14.8k", "82ms"],
          ["POST /purge", "1.1k", "140ms"],
        ],
      },
      { t: "bars", label: "requests per hour", values: [30, 44, 38, 62, 70, 55, 82, 96, 74, 88, 60, 48] },
    ],
  },

  {
    id: "studioflow",
    project: "studioflow",
    prompt: "a booking page for my tattoo studio with deposits",
    target: "web app",
    stack: ["React", "Stripe", "Postgres"],
    spec: { files: 14, cost: "$0.66", time: "~8 min" },
    stages: [S.scaffold, S.db, S.api, S.pay, S.auth, S.security, S.build],
    log: [
      { tone: "coder", text: "building availability engine" },
      { tone: "infra", text: "slot locking · advisory transactions" },
      { tone: "reviewer", text: "auditing booking flow" },
      { tone: "flag", text: "flag · double-book race window" },
      { tone: "ok", text: "row lock + retry · verified" },
      { tone: "infra", text: "deposit captured · replay safe" },
    ],
    files: [
      {
        name: "slots.ts",
        path: "src/server/",
        lines: [
          'import { db } from "./client";',
          "",
          "export async function reserve(slotId: string, user: string) {",
          "  return db.tx(async (t) => {",
          "    const slot = await t.slots.lockForUpdate(slotId);",
          "",
          '    if (slot.status !== "open") {',
          '      throw new Conflict("slot already taken");',
          "    }",
          "",
          "    await t.slots.hold(slotId, user, minutes(10));",
          "    return slot;",
          "  });",
          "}",
        ],
      },
      {
        name: "Booking.tsx",
        path: "src/components/",
        lines: [
          'import { useSlots } from "../lib/useSlots";',
          "",
          "export function Booking({ artist }: Props) {",
          "  const { days, pick, selected } = useSlots(artist);",
          "",
          "  return (",
          '    <div className="booking">',
          "      <DayStrip days={days} onPick={pick} />",
          "      <SlotGrid day={selected} />",
          "      <DepositForm amount={artist.deposit} />",
          "    </div>",
          "  );",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "book a session", title: "Ink & Iron Studio", badge: "$80 deposit" },
      {
        t: "list",
        label: "thursday · may 8",
        rows: [
          { name: "10:00 — 12:00", meta: "open", state: "on" },
          { name: "12:30 — 14:30", meta: "booked", state: "off" },
          { name: "15:00 — 18:00", meta: "open", state: "on" },
          { name: "18:30 — 20:00", meta: "hold", state: "warn" },
        ],
      },
      {
        t: "form",
        label: "confirm booking",
        fields: [
          { name: "artist", value: "Rae · fine line" },
          { name: "session", value: "Thu May 8 · 15:00" },
          { name: "deposit", value: "$80.00 (refundable 48h)" },
        ],
        cta: "pay deposit & confirm",
      },
    ],
  },

  {
    id: "sentinel",
    project: "sentinel",
    prompt: "an uptime monitor that pings my sites and alerts me",
    target: "web app",
    stack: ["Node", "Cron", "Postgres"],
    spec: { files: 11, cost: "$0.50", time: "~7 min" },
    stages: [S.scaffold, S.db, S.api, S.rate, S.perf, S.security, S.build],
    log: [
      { tone: "coder", text: "building probe scheduler" },
      { tone: "infra", text: "multi-region probes · 5 pops" },
      { tone: "reviewer", text: "auditing alert logic" },
      { tone: "flag", text: "flag · alert storm on flapping host" },
      { tone: "ok", text: "hysteresis + 3-strike rule · verified" },
      { tone: "infra", text: "secrets sealed · no keys in logs" },
    ],
    files: [
      {
        name: "probe.ts",
        path: "src/server/",
        lines: [
          "export async function probe(target: Target) {",
          "  const started = performance.now();",
          "",
          "  try {",
          "    const res = await fetch(target.url, {",
          "      signal: AbortSignal.timeout(8000),",
          "    });",
          "",
          "    return {",
          "      ok: res.ok,",
          "      ms: Math.round(performance.now() - started),",
          "      code: res.status,",
          "    };",
          "  } catch {",
          "    return { ok: false, ms: 8000, code: 0 };",
          "  }",
          "}",
        ],
      },
      {
        name: "alerts.ts",
        path: "src/server/",
        lines: [
          "const STRIKES = 3;",
          "",
          "export function shouldAlert(history: Result[]) {",
          "  const recent = history.slice(-STRIKES);",
          "  if (recent.length < STRIKES) return false;",
          "",
          "  const allDown = recent.every((r) => !r.ok);",
          "  const wasUp = history.at(-STRIKES - 1)?.ok ?? true;",
          "",
          "  return allDown && wasUp;",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "monitors", title: "8 endpoints healthy", badge: "all green" },
      {
        t: "kpi",
        items: [
          { label: "uptime 30d", value: "99.98%" },
          { label: "avg", value: "182ms" },
          { label: "incidents", value: "1" },
          { label: "regions", value: "5" },
        ],
      },
      {
        t: "list",
        label: "endpoints",
        rows: [
          { name: "api.acme.com/health", meta: "142ms", state: "on" },
          { name: "acme.com", meta: "168ms", state: "on" },
          { name: "cdn.acme.com", meta: "94ms", state: "on" },
          { name: "staging.acme.com", meta: "degraded", state: "warn" },
        ],
      },
      { t: "bars", label: "response time · 24h", values: [40, 38, 42, 39, 55, 44, 41, 38, 47, 40, 36, 39] },
    ],
  },
];
