import { S, type HeroRun } from "./heroTypes";

/** Runs 01–08. */
export const RUNS_A: HeroRun[] = [
  {
    id: "habitly",
    project: "habitly",
    prompt: "a habit tracker with streaks and a dark UI",
    target: "web app",
    stack: ["React", "Tailwind", "IndexedDB"],
    spec: { files: 9, cost: "$0.42", time: "~6 min" },
    stages: [S.scaffold, S.schema, S.ui, S.state, S.a11y, S.perf, S.build],
    log: [
      { tone: "coder", text: "scaffolding vite + react workspace" },
      { tone: "infra", text: "indexeddb store · offline-first writes" },
      { tone: "reviewer", text: "auditing HabitGrid.tsx" },
      { tone: "flag", text: "flag · stale dependency array" },
      { tone: "ok", text: "auto-fix verified · render trace clean" },
      { tone: "reviewer", text: "a11y pass · contrast AA on 9 files" },
    ],
    files: [
      {
        name: "HabitGrid.tsx",
        path: "src/components/",
        lines: [
          'import { useCallback, useState } from "react";',
          'import type { Habit } from "../lib/types";',
          "",
          "export function HabitGrid({ habits, onSync }: Props) {",
          "  const [rows, setRows] = useState(habits);",
          "",
          "  const toggle = useCallback((id: string, day: number) => {",
          "    setRows((xs) => xs.map((h) =>",
          "      h.id === id ? flipDay(h, day) : h",
          "    ));",
          "    onSync(id, day);",
          "  }, [onSync]);",
          "",
          "  return (",
          '    <section className="grid-7" aria-label="Habit week">',
          "      {rows.map((h) => (",
          "        <HabitRow key={h.id} habit={h} onToggle={toggle} />",
          "      ))}",
          "    </section>",
          "  );",
          "}",
        ],
      },
      {
        name: "streak.ts",
        path: "src/lib/",
        lines: [
          'import type { Habit } from "./types";',
          "",
          "export function longestStreak(habit: Habit): number {",
          "  let best = 0;",
          "  let run = 0;",
          "",
          "  for (const done of habit.days) {",
          "    run = done ? run + 1 : 0;",
          "    if (run > best) best = run;",
          "  }",
          "",
          "  return best;",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "week 32", title: "Tonight's list", badge: "12-day streak" },
      {
        t: "kpi",
        items: [
          { label: "active", value: "5" },
          { label: "done", value: "24", delta: "+6" },
          { label: "best", value: "12d" },
          { label: "rate", value: "68%", delta: "+9%" },
        ],
      },
      {
        t: "list",
        label: "today",
        rows: [
          { name: "Read 20 pages", meta: "12d", state: "on" },
          { name: "Ship code", meta: "5d", state: "on" },
          { name: "Morning run", meta: "3d", state: "off" },
          { name: "No sugar", meta: "8d", state: "on" },
        ],
      },
      {
        t: "heat",
        label: "last 4 weeks",
        rows: [
          [1, 1, 0.6, 1, 1, 0, 0],
          [1, 0.5, 1, 1, 1, 1, 0],
          [0, 1, 1, 0.4, 1, 0, 1],
          [1, 1, 1, 1, 0.7, 0, 0],
        ],
      },
      { t: "bars", label: "monthly momentum", values: [40, 62, 55, 78, 66, 90, 72, 84, 95, 70, 88, 100], caption: "+18%" },
    ],
  },

  {
    id: "invoicely",
    project: "invoicely",
    prompt: "an invoice generator with PDF export and reminders",
    target: "web app",
    stack: ["React", "Postgres", "Stripe"],
    spec: { files: 14, cost: "$0.61", time: "~8 min" },
    stages: [S.scaffold, S.db, S.api, S.pay, S.security, S.tests, S.build],
    log: [
      { tone: "coder", text: "modelling invoice + line items" },
      { tone: "infra", text: "postgres schema · 4 tables migrated" },
      { tone: "reviewer", text: "auditing totals.ts" },
      { tone: "flag", text: "flag · float rounding drift on tax" },
      { tone: "ok", text: "switched to integer cents · verified" },
      { tone: "infra", text: "stripe webhooks · idempotency keys" },
    ],
    files: [
      {
        name: "totals.ts",
        path: "src/lib/",
        lines: [
          'import type { LineItem } from "./types";',
          "",
          "const cents = (n: number) => Math.round(n * 100);",
          "",
          "export function invoiceTotal(items: LineItem[]) {",
          "  const sub = items.reduce(",
          "    (sum, it) => sum + cents(it.rate) * it.qty,",
          "    0,",
          "  );",
          "",
          "  const tax = Math.round(sub * 0.08);",
          "  return { sub, tax, due: sub + tax };",
          "}",
        ],
      },
      {
        name: "webhook.ts",
        path: "src/server/",
        lines: [
          'import { verifySignature } from "./stripe";',
          "",
          "export async function POST(req: Request) {",
          "  const raw = await req.text();",
          '  const sig = req.headers.get("stripe-signature");',
          "",
          "  if (!verifySignature(raw, sig)) {",
          "    return new Response(null, { status: 400 });",
          "  }",
          "",
          "  await markInvoicePaid(JSON.parse(raw));",
          "  return Response.json({ received: true });",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "invoice", title: "#INV-0241", badge: "due in 14d" },
      {
        t: "table",
        cols: ["description", "qty", "amount"],
        rows: [
          ["Landing page design", "1", "$1,800"],
          ["Design system setup", "1", "$1,200"],
          ["Frontend build", "42h", "$4,200"],
          ["Motion + polish", "12h", "$1,080"],
        ],
        total: ["total due", "$8,820.00"],
      },
      {
        t: "kpi",
        items: [
          { label: "paid", value: "$24.1k" },
          { label: "open", value: "$8.8k" },
          { label: "overdue", value: "$0" },
          { label: "avg pay", value: "9d" },
        ],
      },
      {
        t: "feed",
        items: [
          { title: "Reminder scheduled · Northwind", meta: "sends in 3 days" },
          { title: "Invoice #0240 paid", meta: "$3,400 · 2h ago" },
        ],
      },
    ],
  },

  {
    id: "deepfocus",
    project: "deepfocus",
    prompt: "a pomodoro app with lo-fi sounds and session stats",
    target: "web app",
    stack: ["React", "Web Audio", "localStorage"],
    spec: { files: 8, cost: "$0.36", time: "~5 min" },
    stages: [S.scaffold, S.state, S.perf, S.a11y, S.tests, S.build],
    log: [
      { tone: "coder", text: "building timer engine" },
      { tone: "reviewer", text: "auditing useTimer.ts" },
      { tone: "flag", text: "flag · clock drift on tab blur" },
      { tone: "ok", text: "timestamp anchor · verified" },
      { tone: "infra", text: "audio graph · gain ramp, no clipping" },
      { tone: "reviewer", text: "full pass · 8 files clean" },
    ],
    files: [
      {
        name: "useTimer.ts",
        path: "src/lib/",
        lines: [
          'import { useEffect, useRef, useState } from "react";',
          "",
          "export function useTimer(seconds: number) {",
          "  const endsAt = useRef(Date.now() + seconds * 1000);",
          "  const [left, setLeft] = useState(seconds);",
          "",
          "  useEffect(() => {",
          "    const id = setInterval(() => {",
          "      const ms = endsAt.current - Date.now();",
          "      setLeft(Math.max(0, Math.round(ms / 1000)));",
          "    }, 250);",
          "",
          "    return () => clearInterval(id);",
          "  }, []);",
          "",
          "  return left;",
          "}",
        ],
      },
      {
        name: "audio.ts",
        path: "src/lib/",
        lines: [
          "const ctx = new AudioContext();",
          "",
          "export function fadeIn(buffer: AudioBuffer) {",
          "  const src = ctx.createBufferSource();",
          "  const gain = ctx.createGain();",
          "",
          "  src.buffer = buffer;",
          "  src.loop = true;",
          "  gain.gain.setValueAtTime(0, ctx.currentTime);",
          "  gain.gain.linearRampToValueAtTime(0.4, ctx.currentTime + 2);",
          "",
          "  src.connect(gain).connect(ctx.destination);",
          "  src.start();",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "focus", title: "Session 3 of 4", badge: "lo-fi on" },
      { t: "ring", value: "17:42", sub: "remaining", pct: 0.7, actions: ["pause", "skip"] },
      {
        t: "list",
        label: "today",
        rows: [
          { name: "Deep work", meta: "25:00", state: "on" },
          { name: "Short break", meta: "05:00", state: "on" },
          { name: "Deep work", meta: "25:00", state: "on" },
          { name: "Long break", meta: "15:00", state: "off" },
        ],
      },
      { t: "bars", label: "focus this week", values: [60, 80, 45, 95, 70, 30, 85], caption: "14h 20m" },
    ],
  },

  {
    id: "shipdesk",
    project: "shipdesk",
    prompt: "a support inbox with canned replies for my store",
    target: "web app",
    stack: ["React", "WebSocket", "Postgres"],
    spec: { files: 16, cost: "$0.74", time: "~9 min" },
    stages: [S.scaffold, S.db, S.realtime, S.auth, S.rate, S.security, S.build],
    log: [
      { tone: "coder", text: "building conversation model" },
      { tone: "infra", text: "websocket channel · resume tokens" },
      { tone: "reviewer", text: "auditing socket.ts" },
      { tone: "flag", text: "flag · listener leak on unmount" },
      { tone: "ok", text: "cleanup added · verified" },
      { tone: "infra", text: "rate limit · 60 req/min per ip" },
    ],
    files: [
      {
        name: "socket.ts",
        path: "src/lib/",
        lines: [
          "export function connect(room: string, onMsg: Handler) {",
          "  let attempt = 0;",
          "  let ws: WebSocket;",
          "",
          "  const open = () => {",
          "    ws = new WebSocket(`${WS_URL}/${room}`);",
          "    ws.onmessage = (e) => onMsg(JSON.parse(e.data));",
          "    ws.onclose = () => {",
          "      const wait = Math.min(8000, 2 ** attempt++ * 500);",
          "      setTimeout(open, wait);",
          "    };",
          "  };",
          "",
          "  open();",
          "  return () => ws.close();",
          "}",
        ],
      },
      {
        name: "Inbox.tsx",
        path: "src/components/",
        lines: [
          'import { useThreads } from "../lib/useThreads";',
          "",
          "export function Inbox() {",
          "  const { threads, active, select } = useThreads();",
          "",
          "  return (",
          '    <div className="inbox">',
          "      <ThreadList items={threads} onSelect={select} />",
          "      <Conversation thread={active} />",
          "      <ReplyBar suggestions={active.canned} />",
          "    </div>",
          "  );",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "inbox", title: "12 open threads", badge: "live" },
      {
        t: "chat",
        msgs: [
          { who: "them", text: "Hey — where's order #1142?" },
          { who: "me", text: "Checking tracking now, one sec." },
          { who: "me", text: "It's out for delivery, arrives Thursday." },
          { who: "them", text: "Amazing, thank you!" },
        ],
      },
      {
        t: "kpi",
        items: [
          { label: "first reply", value: "42s", delta: "-18s" },
          { label: "resolved", value: "94%" },
          { label: "open", value: "12" },
          { label: "csat", value: "4.8" },
        ],
      },
    ],
  },

  {
    id: "pulseboard",
    project: "pulseboard",
    prompt: "an analytics dashboard for my newsletter",
    target: "web app",
    stack: ["React", "Recharts", "ClickHouse"],
    spec: { files: 13, cost: "$0.58", time: "~7 min" },
    stages: [S.scaffold, S.db, S.api, S.cache, S.perf, S.seo, S.build],
    log: [
      { tone: "coder", text: "building metrics aggregation" },
      { tone: "infra", text: "columnar rollups · 30d retention" },
      { tone: "reviewer", text: "auditing query layer" },
      { tone: "flag", text: "flag · unbounded date range query" },
      { tone: "ok", text: "clamped window + index hint · verified" },
      { tone: "infra", text: "edge cache · swr 60s" },
    ],
    files: [
      {
        name: "rollup.ts",
        path: "src/server/",
        lines: [
          'import { db } from "./client";',
          "",
          "export async function dailyOpens(from: Date, to: Date) {",
          "  const span = clampRange(from, to, 90);",
          "",
          "  return db.query(`",
          "    SELECT toDate(ts) AS day, count() AS opens",
          "    FROM events",
          "    WHERE ts BETWEEN {from:DateTime} AND {to:DateTime}",
          "    GROUP BY day ORDER BY day",
          "  `, span);",
          "}",
        ],
      },
      {
        name: "Chart.tsx",
        path: "src/components/",
        lines: [
          'import { memo } from "react";',
          "",
          "export const Chart = memo(function Chart({ series }: Props) {",
          "  const max = Math.max(...series.map((p) => p.value));",
          "",
          "  return (",
          '    <svg viewBox="0 0 100 40" preserveAspectRatio="none">',
          "      <polyline",
          '        fill="none"',
          '        stroke="currentColor"',
          "        points={toPoints(series, max)}",
          "      />",
          "    </svg>",
          "  );",
          "});",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "last 30 days", title: "Newsletter health", badge: "live" },
      {
        t: "kpi",
        items: [
          { label: "subscribers", value: "12.4k", delta: "+18%" },
          { label: "open rate", value: "62%", delta: "+4%" },
          { label: "clicks", value: "3.1k", delta: "+11%" },
          { label: "churn", value: "0.8%", delta: "-0.3%" },
        ],
      },
      { t: "bars", label: "opens per day", values: [35, 55, 40, 70, 58, 88, 74, 92, 66, 80, 95, 100], caption: "peak Tue" },
      { t: "split", left: "4m 12s", right: "3m 48s", label: "avg read time" },
    ],
  },

  {
    id: "gigboard",
    project: "gigboard",
    prompt: "a job application tracker with a kanban board",
    target: "web app",
    stack: ["React", "dnd-kit", "Supabase"],
    spec: { files: 11, cost: "$0.49", time: "~7 min" },
    stages: [S.scaffold, S.db, S.auth, S.state, S.a11y, S.tests, S.build],
    log: [
      { tone: "coder", text: "building board + drag layer" },
      { tone: "infra", text: "row-level security policies applied" },
      { tone: "reviewer", text: "auditing drag reducer" },
      { tone: "flag", text: "flag · index collision on reorder" },
      { tone: "ok", text: "fractional ranking · verified" },
      { tone: "reviewer", text: "keyboard drag support added" },
    ],
    files: [
      {
        name: "reorder.ts",
        path: "src/lib/",
        lines: [
          "export function rankBetween(a?: string, b?: string) {",
          '  if (!a && !b) return "n";',
          "  if (!a) return prevKey(b!);",
          "  if (!b) return nextKey(a);",
          "",
          "  const mid = midpoint(a, b);",
          "  if (mid === a || mid === b) {",
          '    throw new Error("rank space exhausted");',
          "  }",
          "",
          "  return mid;",
          "}",
        ],
      },
      {
        name: "Board.tsx",
        path: "src/components/",
        lines: [
          'import { DndContext } from "@dnd-kit/core";',
          'import { rankBetween } from "../lib/reorder";',
          "",
          "export function Board({ columns, onMove }: Props) {",
          "  return (",
          "    <DndContext onDragEnd={(e) => onMove(resolve(e))}>",
          '      <div className="board">',
          "        {columns.map((c) => (",
          "          <Column key={c.id} column={c} />",
          "        ))}",
          "      </div>",
          "    </DndContext>",
          "  );",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "pipeline", title: "24 applications", badge: "3 interviews" },
      {
        t: "kanban",
        cols: [
          { name: "applied", items: ["Linear", "Vercel", "Raycast", "Figma"] },
          { name: "interview", items: ["Stripe", "Notion"] },
          { name: "offer", items: ["Anthropic"] },
        ],
      },
      {
        t: "kpi",
        items: [
          { label: "sent", value: "24" },
          { label: "reply rate", value: "38%" },
          { label: "interviews", value: "3" },
          { label: "offers", value: "1" },
        ],
      },
    ],
  },

  {
    id: "shotlist",
    project: "shotlist",
    prompt: "a portfolio site for a photographer with a lightbox",
    target: "web app",
    stack: ["Astro", "Tailwind", "CDN"],
    spec: { files: 10, cost: "$0.44", time: "~6 min" },
    stages: [S.scaffold, S.ui, S.perf, S.seo, S.a11y, S.cache, S.build],
    log: [
      { tone: "coder", text: "building masonry gallery" },
      { tone: "infra", text: "responsive srcset · avif + webp" },
      { tone: "reviewer", text: "auditing image pipeline" },
      { tone: "flag", text: "flag · layout shift on load (CLS 0.21)" },
      { tone: "ok", text: "intrinsic sizing · CLS now 0.01" },
      { tone: "infra", text: "lighthouse 99 · lcp 0.9s" },
    ],
    files: [
      {
        name: "Gallery.astro",
        path: "src/components/",
        lines: [
          "---",
          'import { getImages } from "../lib/images";',
          "const shots = await getImages();",
          "---",
          "",
          '<section class="masonry">',
          "  {shots.map((shot) => (",
          "    <img",
          "      src={shot.src}",
          "      srcset={shot.srcset}",
          "      width={shot.w}",
          "      height={shot.h}",
          '      loading="lazy"',
          "      alt={shot.alt}",
          "    />",
          "  ))}",
          "</section>",
        ],
      },
      {
        name: "images.ts",
        path: "src/lib/",
        lines: [
          "const WIDTHS = [480, 960, 1440, 1920];",
          "",
          "export function buildSrcset(id: string) {",
          "  return WIDTHS",
          "    .map((w) => `${cdn(id, w)} ${w}w`)",
          '    .join(", ");',
          "}",
          "",
          "function cdn(id: string, w: number) {",
          "  return `${CDN}/${id}?w=${w}&fm=avif&q=72`;",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "portfolio", title: "Selected work", badge: "lighthouse 99" },
      {
        t: "cards",
        items: [
          { title: "Coastal series", sub: "18 frames · 2026", tag: "new" },
          { title: "Night market", sub: "24 frames · 2025" },
          { title: "Studio portraits", sub: "12 frames · 2025" },
          { title: "Alpine light", sub: "31 frames · 2024" },
        ],
      },
      {
        t: "kpi",
        items: [
          { label: "lcp", value: "0.9s" },
          { label: "cls", value: "0.01" },
          { label: "inp", value: "84ms" },
          { label: "score", value: "99" },
        ],
      },
    ],
  },

  {
    id: "tabsplit",
    project: "tabsplit",
    prompt: "an app to split bills with friends and settle up",
    target: "web app",
    stack: ["React", "Postgres", "Auth"],
    spec: { files: 12, cost: "$0.53", time: "~7 min" },
    stages: [S.scaffold, S.db, S.auth, S.api, S.security, S.tests, S.build],
    log: [
      { tone: "coder", text: "modelling ledger + balances" },
      { tone: "infra", text: "double-entry ledger · immutable rows" },
      { tone: "reviewer", text: "auditing settle.ts" },
      { tone: "flag", text: "flag · rounding leaves 1c orphan" },
      { tone: "ok", text: "remainder distributed · verified" },
      { tone: "infra", text: "penetration surface reviewed · clean" },
    ],
    files: [
      {
        name: "settle.ts",
        path: "src/lib/",
        lines: [
          "export function split(totalCents: number, people: string[]) {",
          "  const base = Math.floor(totalCents / people.length);",
          "  const remainder = totalCents - base * people.length;",
          "",
          "  return people.map((id, i) => ({",
          "    id,",
          "    owes: base + (i < remainder ? 1 : 0),",
          "  }));",
          "}",
        ],
      },
      {
        name: "balances.ts",
        path: "src/lib/",
        lines: [
          'import type { Entry } from "./types";',
          "",
          "export function netBalances(entries: Entry[]) {",
          "  const net = new Map<string, number>();",
          "",
          "  for (const e of entries) {",
          "    net.set(e.from, (net.get(e.from) ?? 0) - e.cents);",
          "    net.set(e.to, (net.get(e.to) ?? 0) + e.cents);",
          "  }",
          "",
          "  return [...net].map(([id, cents]) => ({ id, cents }));",
          "}",
        ],
      },
    ],
    preview: [
      { t: "head", eyebrow: "trip · lisbon", title: "You are owed $128", badge: "4 people" },
      {
        t: "table",
        cols: ["expense", "paid by", "share"],
        rows: [
          ["Airbnb · 3 nights", "you", "$420"],
          ["Dinner · Time Out", "mika", "$86"],
          ["Rental car", "you", "$210"],
          ["Museum tickets", "sam", "$48"],
        ],
        total: ["your balance", "+$128.00"],
      },
      {
        t: "list",
        label: "settle up",
        rows: [
          { name: "mika owes you", meta: "$64", state: "on" },
          { name: "sam owes you", meta: "$64", state: "on" },
          { name: "you owe jules", meta: "$0", state: "off" },
        ],
      },
    ],
  },
];
